#!/usr/bin/env python3
"""Regenerates bible-data.js from en_kjv.json.

The display is often opened straight off disk (file:///.../index.html), where
browsers block fetch() against local files. Emitting the same data as a plain
classic <script> sidesteps that restriction, because classic scripts are still
allowed across file:// URLs.

Run this whenever en_kjv.json changes:

    python3 build_bible_data.py
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "en_kjv.json"
TARGET = ROOT / "bible-data.js"

# en_kjv.json carries the KJV's own printing apparatus inline:
#   {are}                       supplied words — part of the reading text
#   {firmament: Heb. expansion} translator's note — apparatus, not scripture
#   «{...}»                     book colophon — apparatus
# A projector screen wants the reading text only, so notes and colophons are
# dropped and the supplied-word braces are unwrapped.

# A span is a translator's note when it carries one of these tells.
NOTE_MARKERS = re.compile(
    r":\s"                              # "firmament: Heb. expansion"
    r"|\.\.\."                          # "at the... Heb. at the will"
    r"|\b(?:Heb|Gr|Chal|Syriac|Arab|i\.e)\."
    r"|(?:^|[;,])\s*or,",               # "sickle; or, scythe"
)
# Book colophons ("Written to the Romans from Corinthus…") and marginal
# commentary are long; genuine supplied-word spans are always short phrases.
NOTE_MAX_LENGTH = 34

COLOPHON = re.compile(r"«.*?»", re.DOTALL)
BRACED = re.compile(r"\{([^{}]*)\}")
WHITESPACE = re.compile(r"\s+")


def is_note(span: str) -> bool:
    """Whether a braced span is translator's apparatus rather than reading text."""
    return len(span) > NOTE_MAX_LENGTH or bool(NOTE_MARKERS.search(span))


def clean_verse(text: str) -> str:
    """Strips the KJV printing apparatus, keeping the reading text."""
    text = COLOPHON.sub("", text)

    # Three verses in en_kjv.json close a note early and then leave an extra
    # "}", e.g. "{in yourselves...: or, ...for} yourselves}". The note really
    # runs to the last "}", so collapse that whole region into one span;
    # otherwise the tail ("yourselves") survives as leftover prose.
    if text.count("}") > text.count("{") and "{" in text:
        start, end = text.find("{"), text.rfind("}")
        if end > start:
            inner = text[start + 1:end]
            text = text[:start] + ("" if is_note(inner) else inner) + text[end + 1:]

    text = BRACED.sub(lambda m: "" if is_note(m.group(1)) else m.group(1), text)
    # Any brace still standing was an unmatched opener: drop the punctuation.
    return WHITESPACE.sub(" ", text.replace("{", "").replace("}", "")).strip()


def main() -> None:
    # utf-8-sig: this copy of en_kjv.json starts with a BOM, which bare
    # JSON.parse()/json.loads() reject.
    data = json.loads(SOURCE.read_text(encoding="utf-8-sig"))
    for book in data:
        book["chapters"] = [
            [clean_verse(verse) for verse in chapter] for chapter in book["chapters"]
        ]
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"))

    # These characters would terminate the surrounding <script> block or break
    # string literals in older parsers, so emit them as \u escapes.
    for char, escape in (("<", "\\u003c"), (">", "\\u003e"), ("&", "\\u0026"),
                         ("\u2028", "\\u2028"), ("\u2029", "\\u2029")):
        payload = payload.replace(char, escape)

    TARGET.write_text(
        "/* Generated by build_bible_data.py from en_kjv.json — do not edit by hand. */\n"
        "window.__EWC_BIBLE_DATA__ = " + payload + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {TARGET} ({TARGET.stat().st_size:,} bytes, {len(data)} books)")


if __name__ == "__main__":
    main()
